name: barber_shop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tofino - Regular
      fonts:
        - asset: assets/fonts/Tofino Regular.otf
    - family: Tofino - Bold
      fonts:
        - asset: assets/fonts/Tofino Bold.otf
    - family: Tofino - Black
      fonts:
        - asset: assets/fonts/Tofino Black.otf
    - family: Tofino - Book
      fonts:
        - asset: assets/fonts/Tofino Book.otf
    - family: Tofino - Light
      fonts:
        - asset: assets/fonts/Tofino Light.otf
    - family: Tofino - Medium
      fonts:
        - asset: assets/fonts/Tofino Medium.otf
    - family: Tofino - Thin
      fonts:
        - asset: assets/fonts/Tofino Thin.otf
    - family: Tofino - Ultra
      fonts:
        - asset: assets/fonts/Tofino Ultra.otf
        
